### ISSUE TITLE
Best Time

### ISSUE THREAD

**Issue by scaranti** [AssaEmpireToken/Pancakeswap-Prediction-Bot-NEW-v2.1#7]
Good night, how are you? I'm testing your robot and checking a good time to activate which. Do you have a specific time? Prices not being considered. Thank you very much and congratulations for the work!!!

Alex

**Comment by AssaEmpireToken** [comment]
hay, there is no specific time to use the bot. but I have the feeling that it runs best around noon and in the evening.
